### PR TITLE
Update profile-all.md

### PR DESCRIPTION
**Pull request by abdounikarim**
Hello, i think there's an error here. I just have a hack plan at blackfire and i have access to the "disable distributed profiling" button. 😉

### CODE REVIEW

**Comment by weaverryan** [comment]
Hey @abdounikarim!

Hmm... is it possible you have a "trial" for the Premium level? Their pricing page is pretty clear that "Distributed Profiling" is under the Premium plan - https://blackfire.io/pricing

**Comment by abdounikarim** [comment]
@weaverryan absolutely not. 
I think there's two things : 
- the button "disable distributed profiling" which is activated, even for "hack plan".
- the section, which is only on premium plans.

On the video, you're speaking about the "distributed profiling" when we see the "disable distributed profiling". 

I don't know if i'm clear ?

**Comment by weaverryan** [comment]
Hey @abdounikarim!

Hmm. From my understanding then, ANYONE can see the "Disable Distributed Profiling" checkbox. But only Premium users can actually *see* the distributed profiling data/section in Blackfire. Is that accurate? On your hack plan, are you able to actually see the Distributed Profiler section data?

Cheers!

**Comment by abdounikarim** [comment]
yes, that's it

**Comment by weaverryan** [comment]
Hey @abdounikarim!

Ok! So then, the current text already seems correct, right? We say:

> Distributed profiling is available to Premium plan users or higher

And this appears to be true. If you have a Hack plan, you may see the "disable distributed profiling" button, but you don not actually have access to the distributed profiling. 

This PR removes the above note, which seems incorrect. Am I missing a detail?

Thanks!

**Comment by abdounikarim** [comment]
hey @weaverryan .

You're right. 

I close this.

**Pull request closed without merging**
